export interface AvailablePlugin {
  id: string;
  name: string;
  description: string;
  version: string;
  author: string;
  category: string;
  icon: string;
  features: string[];
  usageInstructions?: string;
  configSchema?: {
    type: string;
    properties: Record<string, any>;
    required?: string[];
  };
}

export const AVAILABLE_PLUGINS: AvailablePlugin[] = [
  // ========== CONTENT & ACTIVITIES ==========
  {
    id: 'advanced-assignments',
    name: 'Advanced Assignments',
    description: 'Extra assignment types, bulk submission tools, plagiarism checking integration, and advanced grading rubrics.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'CONTENT',
    icon: 'FileText',
    features: ['Bulk submissions', 'Plagiarism checker', 'Rubric grading', 'Peer review'],
    usageInstructions: 'After enabling: Go to Teacher Dashboard → My Courses → Select Course → Modules. Click "Add Assignment" to see advanced assignment types including rubrics, peer review settings, and plagiarism check options.',
  },
  {
    id: 'advanced-quizzes',
    name: 'Advanced Quizzes',
    description: 'Advanced question types including matching, drag & drop, hotspot images, ordering, and random question pools.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'CONTENT',
    icon: 'HelpCircle',
    features: ['Matching questions', 'Drag & drop', 'Hotspot questions', 'Question banks'],
    usageInstructions: 'After enabling: Go to Teacher Dashboard → My Courses → Select Course → Create Quiz. You will see new question types: Matching, Drag & Drop, Hotspot, and Ordering.',
  },
  {
    id: 'branching-lessons',
    name: 'Branching Lessons',
    description: 'Create interactive branching scenarios where students make choices that affect their learning path.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'CONTENT',
    icon: 'GitBranch',
    features: ['Decision trees', 'Adaptive paths', 'Personalized learning', 'Analytics'],
    usageInstructions: 'After enabling: Go to Teacher Dashboard → My Courses → Select Course → Add Module → "Branching Lesson". Create decision trees with multiple paths based on student choices.',
  },
  {
    id: 'scorm-h5p',
    name: 'SCORM / H5P Package',
    description: 'Import and display SCORM packages and H5P interactive content with full tracking support.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'CONTENT',
    icon: 'Package',
    features: ['SCORM 1.2 & 2004', 'H5P content types', 'Progress tracking', 'xAPI events'],
    usageInstructions: 'After enabling: Go to Teacher Dashboard → My Courses → Select Course → Add Module → "SCORM/H5P Package". Upload your .zip SCORM file or select an H5P content type.',
  },
  {
    id: 'peer-assessment',
    name: 'Peer Assessment',
    description: 'Students can evaluate each other\'s work with configurable rubrics and anonymous reviews.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'CONTENT',
    icon: 'Users',
    features: ['Anonymous reviews', 'Custom rubrics', 'Calibration', 'Automated分配'],
    usageInstructions: 'After enabling: Go to Teacher Dashboard → My Courses → Select Course → Create Assignment → Enable "Peer Assessment". Configure rubric criteria and review settings.',
  },
  {
    id: 'live-sessions',
    name: 'Live Sessions',
    description: 'Schedule and host live webinar sessions integrated with course content.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'CONTENT',
    icon: 'Video',
    features: ['Video conferencing', 'Screen sharing', 'Attendance tracking', 'Recording'],
    usageInstructions: 'After enabling: Go to Teacher Dashboard → My Courses → Select Course → Add Module → "Live Session". Schedule a session and share the link with students.',
  },

  // ========== GAMIFICATION & ENGAGEMENT ==========
  {
    id: 'badges-certificates',
    name: 'Badges & Certificates',
    description: 'Award custom badges and generate PDF certificates for course completions and achievements.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'GAMIFICATION',
    icon: 'Award',
    features: ['Custom badges', 'PDF certificates', 'Open Badges', 'Auto-award rules'],
    usageInstructions: 'After enabling: Go to Admin Dashboard → Plugins → Configure this plugin. Upload badge images and set certificate templates. Teachers can award badges from their course dashboard. Students view badges in their profile.',
    configSchema: {
      type: 'object',
      properties: {
        certificateTemplate: { type: 'string', default: 'default' },
        autoIssue: { type: 'boolean', default: true },
      },
    },
  },
  {
    id: 'points-leaderboard',
    name: 'Points & Leaderboard',
    description: 'Track and display student points with real-time leaderboards and competitive engagement.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'GAMIFICATION',
    icon: 'Trophy',
    features: ['Point system', 'Leaderboards', 'Daily challenges', 'Team competitions'],
    usageInstructions: 'After enabling: Points are earned automatically from course activities. Go to Student Dashboard to see leaderboard. Teachers can award bonus points from course management.',
  },
  {
    id: 'achievements',
    name: 'Achievements System',
    description: 'Unlockable achievements and milestones that reward students for learning activities.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'GAMIFICATION',
    icon: 'Star',
    features: ['Achievement unlocks', 'Progress tracking', 'Social sharing', 'Custom goals'],
    usageInstructions: 'After enabling: Students automatically unlock achievements based on their learning progress. View achievements in Student Dashboard → Achievements tab. Share achievements to social media.',
  },
  {
    id: 'learning-paths',
    name: 'Learning Paths',
    description: 'Create structured learning paths with prerequisites and optional skill trees.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'GAMIFICATION',
    icon: 'Route',
    features: ['Skill trees', 'Prerequisites', 'Optional modules', 'Progress visualization'],
    usageInstructions: 'After enabling: Go to Teacher Dashboard → My Courses → Select Course → Learning Path. Configure prerequisites and skill trees. Students see their learning path progress.',
  },
  {
    id: 'streaks-rewards',
    name: 'Streaks & Daily Rewards',
    description: 'Encourage daily engagement with login streaks and reward milestones.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'GAMIFICATION',
    icon: 'Flame',
    features: ['Login streaks', 'Daily rewards', 'Streak freeze', 'Milestone bonuses'],
    usageInstructions: 'After enabling: Students automatically track daily login streaks. Streak counter visible on student dashboard. Rewards unlocked at milestone days (7, 30, 100, etc.).',
  },

  // ========== ANALYTICS & REPORTING ==========
  {
    id: 'course-analytics',
    name: 'Course Analytics',
    description: 'Detailed engagement metrics, completion statistics, and student performance dashboards.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'ANALYTICS',
    icon: 'BarChart3',
    features: ['Engagement metrics', 'Completion rates', 'Time tracking', 'Heat maps'],
    usageInstructions: 'After enabling: Go to Teacher Dashboard → Analytics. View detailed course metrics including student engagement heatmaps, completion rates, and time spent on each module.',
  },
  {
    id: 'predictive-analytics',
    name: 'Predictive Analytics',
    description: 'AI-powered dropout risk detection and performance forecasting for early intervention.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'ANALYTICS',
    icon: 'Brain',
    features: ['Dropout prediction', 'Performance forecast', 'Risk alerts', 'Intervention suggestions'],
    usageInstructions: 'After enabling: Go to Teacher Dashboard → Analytics → Risk Dashboard. View at-risk students with intervention suggestions. Configure risk thresholds in plugin settings.',
  },
  {
    id: 'event-logging',
    name: 'Advanced Event Logging',
    description: 'Comprehensive activity logs for admins with filtering, export, and compliance reporting.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'ANALYTICS',
    icon: 'Activity',
    features: ['Audit logs', 'Compliance reports', 'Export to CSV', 'Real-time alerts'],
    usageInstructions: 'After enabling: Go to Admin Dashboard → Analytics → Event Logs. Filter by user, event type, date range. Export logs for compliance audits.',
  },
  {
    id: 'student-insights',
    name: 'Student Insights Dashboard',
    description: 'Individual student dashboards showing learning patterns, strengths, and areas for improvement.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'ANALYTICS',
    icon: 'UserCheck',
    features: ['Learning patterns', 'Skill gaps', 'Recommendations', 'Progress trends'],
    usageInstructions: 'After enabling: Go to Teacher Dashboard → Students → Select Student. View detailed insights including learning patterns, skill gaps, and personalized recommendations.',
  },
  {
    id: 'grade-analytics',
    name: 'Grade Analytics',
    description: 'Visualize grade distributions, identify struggling students, and track improvement over time.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'ANALYTICS',
    icon: 'GraduationCap',
    features: ['Grade distribution', 'Trend analysis', 'Comparative reports', 'Export options'],
    usageInstructions: 'After enabling: Go to Admin Dashboard → Analytics → Grades. View grade distributions, trends, and comparative analysis across courses and time periods.',
  },

  // ========== USER & ROLE MANAGEMENT ==========
  {
    id: 'bulk-user-upload',
    name: 'Bulk User Upload',
    description: 'Import students and teachers via CSV/Excel with automatic role assignment and enrollment.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'USERMGMT',
    icon: 'Upload',
    features: ['CSV import', 'Excel support', 'Bulk enrollment', 'Email notifications'],
    usageInstructions: 'After enabling: Go to Admin Dashboard → Users → Bulk Upload. Download the CSV template, fill in user details, and upload. Users will be created and enrolled automatically.',
  },
  {
    id: 'role-permissions',
    name: 'Role & Permissions',
    description: 'Fine-grained permission system with custom roles and capability management.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'USERMGMT',
    icon: 'Shield',
    features: ['Custom roles', 'Capability matrix', 'Role hierarchy', 'Permission groups'],
    usageInstructions: 'After enabling: Go to Admin Dashboard → Users → Roles. Create custom roles and configure permissions. Assign roles to users from the user management page.',
  },
  {
    id: 'cohorts-groups',
    name: 'Cohorts & Groups',
    description: 'Group students into cohorts or learning groups for courses, assignments, or communications.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'USERMGMT',
    icon: 'Users',
    features: ['Dynamic groups', 'Cohort enrollment', 'Group assignments', 'Group messaging'],
    usageInstructions: 'After enabling: Go to Admin Dashboard → Users → Cohorts. Create cohorts and add students. Use cohorts for targeted enrollment and group messaging.',
  },
  {
    id: 'self-registration',
    name: 'Self Registration',
    description: 'Customizable registration forms with approval workflows and custom profile fields.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'USERMGMT',
    icon: 'UserPlus',
    features: ['Custom forms', 'Approval workflow', 'Profile fields', 'Domain restriction'],
    usageInstructions: 'After enabling: Configure from Admin Dashboard → Users → Registration Settings. Set up custom fields and approval workflows. Share registration link with learners.',
  },
  {
    id: 'parent-portal',
    name: 'Parent/Guardian Portal',
    description: 'Allow parents to monitor student progress, attendance, and communicate with teachers.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'USERMGMT',
    icon: 'Home',
    features: ['Progress monitoring', 'Attendance reports', 'Teacher contact', 'Notifications'],
    usageInstructions: 'After enabling: Parents can register separately and link to student accounts. Go to Parent Dashboard to monitor child\'s progress and contact teachers.',
  },

  // ========== COMMUNICATION & COLLABORATION ==========
  {
    id: 'forums',
    name: 'Discussion Forums',
    description: 'Threaded discussions with categories, tags, moderation tools, and reputation system.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'COMMUNICATION',
    icon: 'MessageSquare',
    features: ['Nested threads', 'Categories', 'Moderation', 'Upvoting'],
    usageInstructions: 'After enabling: Go to any Course → Discussions tab. Create forum categories. Students can start discussions, reply, and upvote. Moderate from the dashboard.',
  },
  {
    id: 'chat-messaging',
    name: 'Chat & Direct Messaging',
    description: 'Real-time chat and direct messaging between students and teachers.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'COMMUNICATION',
    icon: 'MessageCircle',
    features: ['Real-time chat', 'Direct messages', 'Group chats', 'File sharing'],
    usageInstructions: 'After enabling: Chat icon appears in the sidebar. Click to open conversations. Create group chats for study groups. Share files directly in chat.',
  },
  {
    id: 'announcements',
    name: 'Announcements',
    description: 'Course-wide and platform-wide announcements with scheduling and targeting.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'COMMUNICATION',
    icon: 'Megaphone',
    features: ['Scheduling', 'Targeted delivery', 'Email digest', 'Pin to top'],
    usageInstructions: 'After enabling: Go to Teacher Dashboard → Course → Announcements. Create announcements with scheduling options. Target specific groups or send to all students.',
  },
  {
    id: 'notifications',
    name: 'Email & Push Notifications',
    description: 'Configurable notifications for assignments, grades, deadlines, and course updates.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'COMMUNICATION',
    icon: 'Bell',
    features: ['Email templates', 'Push notifications', 'Digest mode', 'Quiet hours'],
    usageInstructions: 'After enabling: Configure from Admin Dashboard → Settings → Notifications. Set up email templates and notification preferences. Students receive updates via email and push.',
    configSchema: {
      type: 'object',
      properties: {
        emailNotifications: { type: 'boolean', default: true },
        pushNotifications: { type: 'boolean', default: true },
        digestMode: { type: 'boolean', default: false },
      },
    },
  },
  {
    id: 'video-conference',
    name: 'Video Conferencing',
    description: 'Built-in video meetings integrated with course scheduling and recordings.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'COMMUNICATION',
    icon: 'Video',
    features: ['HD video', 'Screen sharing', 'Breakout rooms', 'Recording'],
    usageInstructions: 'After enabling: Go to Course → Live Sessions. Schedule video meetings with automatic calendar invites. Recordings saved automatically to course materials.',
  },

  // ========== PAYMENTS & ECOMMERCE ==========
  {
    id: 'razorpay-gateway',
    name: 'Razorpay Payment Gateway',
    description: 'Accept payments via Razorpay with support for cards, UPI, wallets, and net banking.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'PAYMENTS',
    icon: 'CreditCard',
    features: ['UPI & Cards', 'Wallets', 'Net banking', 'Refund support'],
    usageInstructions: 'After enabling: Configure API keys from Admin Dashboard → Plugins → Configure. Students can purchase courses using UPI, cards, wallets, or net banking.',
    configSchema: {
      type: 'object',
      properties: {
        keyId: { type: 'string' },
        keySecret: { type: 'string' },
        webhookSecret: { type: 'string' },
      },
      required: ['keyId', 'keySecret'],
    },
  },
  {
    id: 'subscriptions',
    name: 'Subscription Plans',
    description: 'Monthly, quarterly, and yearly subscription models with tiered pricing.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'PAYMENTS',
    icon: 'RefreshCw',
    features: ['Multiple tiers', 'Trial periods', 'Upgrade/downgrade', 'Usage limits'],
    usageInstructions: 'After enabling: Go to Admin Dashboard → Subscriptions. Create subscription plans with different tiers. Students subscribe for unlimited course access.',
  },
  {
    id: 'coupons-discounts',
    name: 'Coupons & Discounts',
    description: 'Create promotional codes, bulk discounts, and seasonal offers.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'PAYMENTS',
    icon: 'Tag',
    features: ['Percentage off', 'Fixed discount', 'Bulk pricing', 'Expiry dates'],
    usageInstructions: 'After enabling: Go to Admin Dashboard → Coupons. Create discount codes with usage limits and expiry dates. Share codes with students for special offers.',
  },
  {
    id: 'affiliate-program',
    name: 'Affiliate Program',
    description: 'Track and manage affiliate referrals with commission payouts.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'PAYMENTS',
    icon: 'Link',
    features: ['Referral tracking', 'Commission rates', 'Payout system', 'Dashboard'],
    usageInstructions: 'After enabling: Go to Admin Dashboard → Affiliates. Create affiliate accounts with custom commission rates. Track referrals and manage payouts.',
  },
  {
    id: 'invoice-billing',
    name: 'Invoice & Billing',
    description: 'Generate professional invoices and manage billing for organizations.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'PAYMENTS',
    icon: 'File',
    features: ['Auto-invoicing', 'Tax handling', 'Organization billing', 'Payment reminders'],
    usageInstructions: 'After enabling: Go to Admin Dashboard → Invoices. Create invoices for organizations. Automatic tax calculation and payment reminders.',
  },

  // ========== INTEGRATIONS ==========
  {
    id: 'lti-tools',
    name: 'LTI External Tools',
    description: 'Connect external learning platforms and tools via LTI 1.3 standard.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'INTEGRATIONS',
    icon: 'Plug',
    features: ['LTI 1.3', 'Deep linking', 'Assignment services', 'Grade sync'],
    usageInstructions: 'After enabling: Go to Admin Dashboard → Integrations → LTI Tools. Add external tool URLs. Teachers can embed external content in their courses.',
  },
  {
    id: 'video-hosting',
    name: 'Video Hosting Integration',
    description: 'Integrate with YouTube, Vimeo, or custom video hosting with streaming optimization.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'INTEGRATIONS',
    icon: 'Play',
    features: ['YouTube embed', 'Vimeo support', 'HLS streaming', 'Adaptive quality'],
    usageInstructions: 'After enabling: Configure video provider from Admin Dashboard → Integrations → Video. Teachers can embed videos from YouTube, Vimeo, or upload directly.',
  },
  {
    id: 'calendar-sync',
    name: 'Calendar & Scheduling',
    description: 'Sync deadlines, live sessions, and events with Google Calendar or Outlook.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'INTEGRATIONS',
    icon: 'Calendar',
    features: ['Google Calendar', 'Outlook sync', 'iCal export', 'Deadline reminders'],
    usageInstructions: 'After enabling: Go to Settings → Integrations → Calendar. Connect Google Calendar or Outlook. Deadlines and sessions automatically sync.',
  },
  {
    id: 'zoom-integration',
    name: 'Zoom Integration',
    description: 'Schedule and embed Zoom meetings directly within course modules.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'INTEGRATIONS',
    icon: 'Video',
    features: ['Meeting scheduling', 'Auto-create links', 'Attendance sync', 'Recordings'],
    usageInstructions: 'After enabling: Configure Zoom API keys from Admin Dashboard → Plugins → Configure. Go to Course → Add Module → Zoom Meeting. Schedule meetings with auto-generated links.',
    configSchema: {
      type: 'object',
      properties: {
        apiKey: { type: 'string' },
        apiSecret: { type: 'string' },
      },
      required: ['apiKey', 'apiSecret'],
    },
  },
  {
    id: 'slack-integration',
    name: 'Slack Integration',
    description: 'Receive notifications and updates in Slack channels for courses and assignments.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'INTEGRATIONS',
    icon: 'Hash',
    features: ['Channel notifications', 'Direct messages', 'Assignment alerts', 'Grade updates'],
    usageInstructions: 'After enabling: Configure Slack webhook from Admin Dashboard → Plugins → Configure. Set up channel notifications for specific events.',
  },
  {
    id: 'webhook-system',
    name: 'Webhook System',
    description: 'Send webhook events to external systems for automation and integration.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'INTEGRATIONS',
    icon: 'Webhook',
    features: ['Custom webhooks', 'Event filtering', 'Retry logic', 'Payload templates'],
    usageInstructions: 'After enabling: Go to Admin Dashboard → Integrations → Webhooks. Add webhook URLs and configure event triggers. External systems receive real-time updates.',
  },

  // ========== AI & AUTOMATION ==========
  {
    id: 'ai-content-generator',
    name: 'AI Content Generator',
    description: 'Auto-generate lessons, quizzes, flashcards, and summaries using AI.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'AI',
    icon: 'Sparkles',
    features: ['Lesson generation', 'Quiz creation', 'Flashcards', 'Summaries'],
    usageInstructions: 'After enabling: Configure API key from Admin Dashboard → Plugins → Configure. Go to Teacher Dashboard → AI Tools. Select a topic to generate course content automatically.',
    configSchema: {
      type: 'object',
      properties: {
        apiKey: { type: 'string' },
        model: { type: 'string', default: 'claude-3-5-sonnet' },
        maxTokens: { type: 'number', default: 4000 },
      },
      required: ['apiKey'],
    },
  },
  {
    id: 'ai-recommendations',
    name: 'Personalized Recommendations',
    description: 'AI-powered course and content recommendations based on student progress.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'AI',
    icon: 'Lightbulb',
    features: ['Course suggestions', 'Learning paths', 'Content relevance', 'Skill mapping'],
    usageInstructions: 'After enabling: Students see personalized course recommendations on the dashboard. Go to Student Dashboard → Recommended Courses for AI-powered suggestions.',
  },
  {
    id: 'ai-auto-grading',
    name: 'AI Auto-Grading',
    description: 'Automatically grade quizzes and written assignments using AI.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'AI',
    icon: 'CheckCircle',
    features: ['Quiz grading', 'Written response grading', 'Plagiarism detection', 'Feedback generation'],
    usageInstructions: 'After enabling: Configure API key from Admin Dashboard → Plugins → Configure. When students submit quizzes or assignments, AI provides instant grading and feedback.',
    configSchema: {
      type: 'object',
      properties: {
        apiKey: { type: 'string' },
        strictness: { type: 'string', default: 'medium' },
      },
      required: ['apiKey'],
    },
  },
  {
    id: 'ai-chatbot',
    name: 'AI Learning Assistant',
    description: 'AI chatbot to answer student questions and provide 24/7 learning support.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'AI',
    icon: 'Bot',
    features: ['Q&A support', 'Course context', 'Multilingual', 'Escalation support'],
    usageInstructions: 'After enabling: Configure from Admin Dashboard → Plugins → Configure. Chatbot appears on course pages. Students ask questions and get instant AI-powered answers.',
    configSchema: {
      type: 'object',
      properties: {
        apiKey: { type: 'string' },
        persona: { type: 'string', default: 'helpful' },
      },
      required: ['apiKey'],
    },
  },
  {
    id: 'ai-translation',
    name: 'AI Translation',
    description: 'Automatic translation of course content to multiple languages.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'AI',
    icon: 'Languages',
    features: ['50+ languages', 'Content localization', 'Multilingual UI', 'RTL support'],
    usageInstructions: 'After enabling: Go to Course Settings → Translation. Select target languages. AI translates all course content automatically. Students see content in their preferred language.',
    configSchema: {
      type: 'object',
      properties: {
        apiKey: { type: 'string' },
        defaultLanguage: { type: 'string', default: 'en' },
      },
      required: ['apiKey'],
    },
  },
  {
    id: 'smart-search',
    name: 'Smart Content Search',
    description: 'AI-powered semantic search across all course content and discussions.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'AI',
    icon: 'Search',
    features: ['Semantic search', 'Natural language queries', 'Related content', 'Voice search'],
    usageInstructions: 'After enabling: Use the search bar in the header. Search understands natural language queries and finds relevant content across all courses.',
  },

  // ========== UTILITY & ADMIN ==========
  {
    id: 'backup-restore',
    name: 'Backup & Restore',
    description: 'Export and import courses, user data, and settings with scheduled backups.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'UTILITY',
    icon: 'Database',
    features: ['Full backup', 'Selective export', 'Scheduled backups', 'One-click restore'],
    usageInstructions: 'After enabling: Go to Admin Dashboard → Settings → Backup. Create manual backups or set up scheduled backups. Restore from previous backups with one click.',
  },
  {
    id: 'custom-themes',
    name: 'Custom Themes',
    description: 'Change the look and feel of the platform with custom themes and branding.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'UTILITY',
    icon: 'Palette',
    features: ['Theme editor', 'Custom branding', 'CSS variables', 'Logo upload'],
    usageInstructions: 'After enabling: Go to Admin Dashboard → Settings → Appearance. Upload your logo, choose colors, and customize the theme. Preview changes before publishing.',
  },
  {
    id: 'multi-language',
    name: 'Multi-Language Support',
    description: 'Translate the platform interface to any language with RTL support.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'UTILITY',
    icon: 'Globe',
    features: ['100+ languages', 'RTL support', 'Custom translations', 'Language switcher'],
    usageInstructions: 'After enabling: Go to Admin Dashboard → Settings → Language. Select default language. Users can switch languages from their profile settings.',
  },
  {
    id: 'custom-fields',
    name: 'Custom Profile Fields',
    description: 'Add custom fields to user profiles and course metadata.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'UTILITY',
    icon: 'FormInput',
    features: ['Field builder', 'Validation rules', 'Conditional display', 'Export data'],
    usageInstructions: 'After enabling: Go to Admin Dashboard → Settings → Custom Fields. Create custom profile fields (e.g., Employee ID, Department). Fields appear in registration and profile forms.',
  },
  {
    id: 'wizard-setup',
    name: 'Setup Wizard',
    description: 'Step-by-step onboarding wizard for new administrators.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'UTILITY',
    icon: 'Wand',
    features: ['Guided setup', 'Sample content', 'Admin training', 'System check'],
    usageInstructions: 'After enabling: New admins see the setup wizard on first login. Follow step-by-step guidance to configure the platform, import sample content, and learn features.',
  },
  {
    id: 'api-access',
    name: 'API Access & Webhooks',
    description: 'REST API for third-party integrations with OAuth 2.0 authentication.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'UTILITY',
    icon: 'Code',
    features: ['REST API', 'OAuth 2.0', 'API keys', 'Rate limiting'],
    usageInstructions: 'After enabling: Go to Admin Dashboard → Settings → API Access. Generate API keys for external integrations. View API documentation for endpoints.',
  },
  {
    id: 'attendance-tracking',
    name: 'Attendance Tracking',
    description: 'Track student attendance for live sessions and course activities.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'UTILITY',
    icon: 'CalendarCheck',
    features: ['Session tracking', 'Auto-attendance', 'Reports', 'Excused absences'],
    usageInstructions: 'After enabling: Go to Course → Attendance. View attendance for live sessions and activities. Mark excused absences. Download attendance reports.',
  },
  {
    id: 'digital-wallet',
    name: 'Digital Wallet',
    description: 'Students can add funds to their wallet for faster course purchases.',
    version: '1.0.0',
    author: 'LMS Team',
    category: 'UTILITY',
    icon: 'Wallet',
    features: ['Add funds', 'Balance history', 'Auto-pay', 'Refunds'],
    usageInstructions: 'After enabling: Students see Wallet option in their profile. Add funds via payment gateway. Wallet balance used for course purchases. Automatic refunds to wallet.',
  },
];

export const PLUGIN_CATEGORIES = [
  { id: 'ALL', name: 'All Plugins', icon: 'Grid' },
  { id: 'CONTENT', name: 'Content & Activities', icon: 'FileText' },
  { id: 'GAMIFICATION', name: 'Gamification', icon: 'Trophy' },
  { id: 'ANALYTICS', name: 'Analytics & Reporting', icon: 'BarChart3' },
  { id: 'USERMGMT', name: 'User & Role Management', icon: 'Users' },
  { id: 'COMMUNICATION', name: 'Communication', icon: 'MessageSquare' },
  { id: 'PAYMENTS', name: 'Payments & eCommerce', icon: 'CreditCard' },
  { id: 'INTEGRATIONS', name: 'Integrations', icon: 'Plug' },
  { id: 'AI', name: 'AI & Automation', icon: 'Sparkles' },
  { id: 'UTILITY', name: 'Utility & Admin', icon: 'Settings' },
];

export const getPluginsByCategory = (category: string) => {
  if (category === 'ALL') return AVAILABLE_PLUGINS;
  return AVAILABLE_PLUGINS.filter(p => p.category === category);
};
