export enum VideoGenStatus {
  PENDING = 'PENDING',
  SCRIPT_GENERATED = 'SCRIPT_GENERATED',
  AUDIO_GENERATED = 'AUDIO_GENERATED',
  VIDEO_RENDERING = 'VIDEO_RENDERING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}
